---
## install python 
hosts: all
  remote_user: ubuntu
  become: true
  gather_facts: no
    
  pre_tasks:
     #raw: apt install python python-apt
     - name: 'install python2'
       apt: 
         name: python
         state: present

- hosts: all
  remote_user: ubuntu
  become: true
  become_method: sudo

  roles:
    - { role: geerlingguy.docker }
    - { role: rfhayashi.ansible-container }
